#! /bin/csh
rm acs_etc_cases.txt acs_etc_cases_subset.txt
rm stis_etc_cases.txt stis_etc_cases_subset.txt
rm nicmos_etc_cases.txt nicmos_etc_cases_subset.txt
rm nicmos_etc_thermback_cases.txt

rm wfc3_ir_imaging_78_cases_subset.txt
rm wfc3_ir_imaging_78_cases.txt
rm wfc3_ir_imaging_80_thermback_subset.txt
rm wfc3_ir_imaging_80_thermback.txt
rm wfc3_ir_spec_61_cases_subset.txt
rm wfc3_ir_spec_61_cases.txt
rm wfc3_ir_spec_62_thermback.txt
rm wfc3_uvis1_imaging_61_cases_subset.txt
rm wfc3_uvis1_imaging_61_cases.txt
rm wfc3_uvis1_spec_62_cases_subset.txt
rm wfc3_uvis1_spec_62_cases.txt
rm wfc3_uvis2_imaging_18_cases_subset.txt
rm wfc3_uvis2_imaging_18_cases.txt
rm wfc3_uvis2_spec_18_cases_subset.txt
rm wfc3_uvis2_spec_18_cases.txt
