#! /bin/csh
rm wfc3_uvis1_imaging_61_cases.py wfc3UVIS1ImagingPysynphotLog_parsed.txt wfc3_uvis1_imaging_61_cases.pickle wfc3_uvis1_imaging_61_cases_parsed.txt wfc3_uvis1_imaging_61_cases_parsed.pickle wfc3_uvis1_imaging_61_cases_parsed.py


rm wfc3_uvis2_imaging_18_cases.py wfc3UVIS2ImagingPysynphotLog_parsed.txt wfc3_uvis2_imaging_18_cases.pickle wfc3_uvis2_imaging_18_cases_parsed.txt wfc3_uvis2_imaging_18_cases_parsed.pickle wfc3_uvis2_imaging_18_cases_parsed.py 

rm wfc3_uvis1_spec_62_cases.py wfc3UVIS1SpecPysynphotLog_parsed.txt wfc3_uvis1_spec_62_cases.pickle wfc3_uvis1_spec_62_cases_parsed.txt wfc3_uvis1_spec_62_cases_parsed.pickle wfc3_uvis1_spec_62_cases_parsed.py

rm wfc3_uvis2_spec_18_cases.py wfc3UVIS2SpecPysynphotLog_parsed.txt wfc3_uvis2_spec_18_cases.pickle wfc3_uvis2_spec_18_cases_parsed.txt wfc3_uvis2_spec_18_cases_parsed.pickle wfc3_uvis2_spec_18_cases_parsed.py

rm wfc3_ir_imaging_78_cases_parsed.txt wfc3_ir_imaging_78_cases_parsed.pickle wfc3_ir_imaging_78_cases.py wfc3_irim_thermback_parsed.txt wfc3_irim_cases_parsed.txt wfc3IRImagingPysynphotLog_parsed.txt wfc3_ir_imaging_78_cases_parsed.py wfc3_ir_imaging_80_thermback.py wfc3_ir_imaging_80_thermback.pickle wfc3_ir_imaging_80_thermback_parsed.txt wfc3_ir_imaging_80_thermback_parsed.pickle wfc3_ir_imaging_80_thermback_parsed.py wfc3_ir_imaging_78_cases.pickle wfc3_irim_cases_parsed.pickle wfc3_irim_thermback_parsed.pickle

rm wfc3_ir_spec_61_cases_parsed.txt wfc3_ir_spec_61_cases_parsed.pickle wfc3_ir_spec_61_cases.py wfc3_irsp_thermback_parsed.txt wfc3_irsp_cases_parsed.txt wfc3_ir_spec_61_cases_parsed.py wfc3_ir_spec_61_cases.pickle wfc3_irsp_cases_parsed.pickle wfc3_irsp_thermback_parsed.pickle wfc3_ir_spec_62_thermback_parsed.txt wfc3_ir_spec_62_thermback_parsed.pickle wfc3_ir_spec_62_thermback.pickle wfc3_ir_spec_62_thermback.py wfc3IRSpecPysynphotLog_parsed.txt wfc3_ir_spec_62_thermback_parsed.py


rm process_wfc3.log
